// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Utility, root, _ref;

  root = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  root.Utility = Utility = (function() {
    var _isFunction, _parser, _toString;

    function Utility() {}

    _parser = null;

    Utility.toString = _toString = Object.prototype.toString;

    Utility.isString = function(obj) {
      return !!(obj === '' || (obj && obj.charCodeAt && obj.substring));
    };

    Utility.isArray = Array.isArray != null ? Array.isArray : function(obj) {
      return _toString.call(obj) === '[object Array]';
    };

    Utility.isNumber = function(obj) {
      return (obj === +obj) || _toString.call(obj) === '[object Number]';
    };

    Utility.isFunction = _isFunction = function(obj) {
      return !!(obj && obj.constructor && obj.call && obj.apply);
    };

    Utility.isExpression = function(obj) {
      return _isFunction(obj != null ? obj.evaluate : void 0);
    };

    Utility.parse = (function() {
      var cache;
      cache = {};
      return function(code) {
        var expression;
        if (cache.hasOwnProperty(code)) {
          return cache[code];
        }
        if (_parser == null) {
          _parser = require('./Parser');
        }
        expression = _parser.parse(code);
        return cache[code] = cache['' + expression] = expression;
      };
    })();

    return Utility;

  })();

}).call(this);

/*
//@ sourceMappingURL=Utility.map
*/
