// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>  

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var ELEMENT_NODE, Level1NodeTypeMatcher, Traversal, exports, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ELEMENT_NODE = require('../Node').Node.ELEMENT_NODE;

  Traversal = require('../Traversal').Traversal;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Level1NodeTypeMatcher = Level1NodeTypeMatcher = (function(_super) {
    __extends(Level1NodeTypeMatcher, _super);

    function Level1NodeTypeMatcher() {
      _ref1 = Level1NodeTypeMatcher.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Level1NodeTypeMatcher.prototype.collect = function(node) {
      var result;
      result = [];
      for (var child = node.firstChild; child; child = child.nextSibling) {
        if (child.nodeType == ELEMENT_NODE) {
          result.push(child);
        }
      };
      return result;
    };

    Level1NodeTypeMatcher.create = function(callback) {
      return new Level1NodeTypeMatcher(callback);
    };

    return Level1NodeTypeMatcher;

  })(Traversal);

}).call(this);

/*
//@ sourceMappingURL=Level1NodeTypeMatcher.map
*/
