// Generated by CoffeeScript 1.7.1

/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>  

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
 */

(function() {
  var DOCUMENT_NODE, Level2NodeIterator, Traversal, exports, ownerDocument, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DOCUMENT_NODE = require('../Node').Node.DOCUMENT_NODE;

  ownerDocument = require('../Document').Document.ownerDocument;

  Traversal = require('../Traversal').Traversal;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Level2NodeIterator = Level2NodeIterator = (function(_super) {
    __extends(Level2NodeIterator, _super);

    function Level2NodeIterator() {
      return Level2NodeIterator.__super__.constructor.apply(this, arguments);
    }

    Level2NodeIterator.prototype.filter = NodeFilter.SHOW_ELEMENT;

    Level2NodeIterator.prototype.options = null;

    Level2NodeIterator.prototype.run = function(root) {
      return this.process(root, this.prepare(root));
    };

    Level2NodeIterator.prototype.prepare = function(root) {
      return this.collect(root, ownerDocument(root));
    };

    Level2NodeIterator.prototype.collect = function(root, doc) {
      return doc.createNodeIterator(root, this.filter, this.options, false);
    };

    Level2NodeIterator.prototype.process = function(root, iterator) {
      var node;
      if (root.nodeType == DOCUMENT_NODE) {
        this.callback(root);
      }
      while (node = iterator.nextNode()) {
        this.callback(node);
      }
      return this;
    };

    Level2NodeIterator.create = function(callback) {
      return new Level2NodeIterator(callback);
    };

    return Level2NodeIterator;

  })(Traversal);

}).call(this);

//# sourceMappingURL=Level2NodeIterator.map
