// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 [Stephan Jorek](stephan.jorek@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Level1NodeTypeMatcher, Level4ElementChildrenIterator, Node, exports, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = require('goatee/Core/Node').Node;

  Level1NodeTypeMatcher = require('goatee/Dom/Traversal/Level1NodeTypeMatcher').Level1NodeTypeMatcher;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Level4ElementChildrenIterator = Level4ElementChildrenIterator = (function(_super) {
    __extends(Level4ElementChildrenIterator, _super);

    function Level4ElementChildrenIterator() {
      _ref1 = Level4ElementChildrenIterator.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Level4ElementChildrenIterator.prototype.collect = function(node) {
      var child, _i, _len, _ref2, _results;
      _ref2 = node.children;
      _results = [];
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        child = _ref2[_i];
        if (child.nodeType == Node.ELEMENT_NODE) {
          _results.push(child);
        }
      }
      return _results;
    };

    return Level4ElementChildrenIterator;

  })(Level1NodeTypeMatcher);

  Level4ElementChildrenIterator.create = function(callback) {
    return new Level4ElementChildrenIterator(callback);
  };

}).call(this);

/*
//@ sourceMappingURL=Level4ElementChildrenIterator.map
*/
