// Generated by CoffeeScript 1.7.1

/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>  

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
 */

(function() {
  var ELEMENT_NODE, Level1NodeTypeMatcher, Level2ChildNodes, exports, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ELEMENT_NODE = require('../Node').Node.ELEMENT_NODE;

  Level1NodeTypeMatcher = require('../Traversal').Level1NodeTypeMatcher;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Level2ChildNodes = Level2ChildNodes = (function(_super) {
    __extends(Level2ChildNodes, _super);

    function Level2ChildNodes() {
      return Level2ChildNodes.__super__.constructor.apply(this, arguments);
    }

    Level2ChildNodes.prototype.collect = function(node) {
      var child, _i, _len, _ref1, _results;
      _ref1 = node.childNodes;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        child = _ref1[_i];
        if (child.nodeType == Node.ELEMENT_NODE) {
          _results.push(child);
        }
      }
      return _results;
    };

    Level2ChildNodes.create = function(callback) {
      return new Level2ChildNodes(callback);
    };

    return Level2ChildNodes;

  })(Traversal);

}).call(this);

//# sourceMappingURL=Level2ChildNodes.map
