// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Level1NodeTypeMatcher, Level4ElementChildrenIterator, node, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  node = require('goatee/Dom/Node');

  Level1NodeTypeMatcher = require('goatee/Dom/Traversal/Level1NodeTypeMatcher');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Level4ElementChildrenIterator = Level4ElementChildrenIterator = (function(_super) {
    __extends(Level4ElementChildrenIterator, _super);

    function Level4ElementChildrenIterator() {
      _ref = Level4ElementChildrenIterator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Level4ElementChildrenIterator.prototype.collect = function(node) {
      var child, _i, _len, _ref1, _results;
      _ref1 = node.children;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        child = _ref1[_i];
        if (child.nodeType == node.ELEMENT_NODE) {
          _results.push(child);
        }
      }
      return _results;
    };

    return Level4ElementChildrenIterator;

  })(Level1NodeTypeMatcher);

  Level4ElementChildrenIterator.create = function(callback) {
    return new Level4ElementChildrenIterator(callback);
  };

}).call(this);
