// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>  
© Copyright 2006 Google Inc. <http://www.google.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Constants, Context, Expression, exports, _ref,
    __hasProp = {}.hasOwnProperty;

  Constants = require('goatee/Core/Constants').Constants;

  Expression = require('goatee/Action/Expression/Javascript').Javascript;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Context = Context = (function() {
    var _evaluate;

    Context.prototype._variables = {};

    Context.prototype._data = null;

    function Context(data, parent) {
      var name, value, variables;
      variables = parent != null ? parent._variables : Context._globals;
      for (name in variables) {
        if (!__hasProp.call(variables, name)) continue;
        value = variables[name];
        this._variables[name] = value;
      }
      this._variables[Constants.VAR_this] = data;
      this._variables[Constants.VAR_context] = this;
      this._data = data != null ? data : Constants.STRING_empty;
      if (parent == null) {
        this._variables[Constants.VAR_top] = this._data;
      }
    }

    Context.prototype.execute = function(fn, template) {
      var e;
      try {
        return fn.call(template, this._variables, this._data);
      } catch (_error) {
        e = _error;
        console.log("Exception " + e + " while executing " + fn + " on " + template);
      }
      return Context._globals[Constants.GLOB_default];
    };

    Context.prototype.clone = function(data, index, count) {
      var ret;
      ret = Context.create(data, this);
      ret.set(Constants.VAR_index, index);
      ret.set(Constants.VAR_count, count);
      return ret;
    };

    Context.prototype.set = function(name, value) {
      this._variables[name] = value;
    };

    Context.prototype.get = function(name) {
      return this._variables[name];
    };

    _evaluate = null;

    Context.prototype.evaluate = function(expression, template) {
      var fn;
      fn = (_evaluate != null ? _evaluate : _evaluate = Expression.get().evaluateToFunction)(expression);
      return this.execute(fn, template);
    };

    Context._globals = {};

    Context.setGlobal = function(name, value) {
      return Context._globals[name] = value;
    };

    Context.setGlobal(Constants.GLOB_default, null);

    Context._recycled = [];

    Context.create = function(data, parent) {
      var instance;
      if (Context._recycled.length > 0) {
        instance = Context._recycle.pop();
        Context.call(instance, data, parent);
        return instance;
      }
      return new Context(data, parent);
    };

    Context.recycle = function(instance) {
      var name, _ref1;
      _ref1 = instance._variables;
      for (name in _ref1) {
        if (!__hasProp.call(_ref1, name)) continue;
        delete instance._variables[name];
      }
      instance._data = null;
      return Context._recycled.push(instance);
    };

    return Context;

  })();

}).call(this);

/*
//@ sourceMappingURL=Context.map
*/
