// Generated by CoffeeScript 1.7.1

/*
© Copyright 2013-2014 Stephan Jorek <stephan.jorek@gmail.com>  
© Copyright 2006 Google Inc. <http://www.google.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
 */

(function() {
  var Context, Expression, GLOB_default, STRING_empty, VAR_context, VAR_count, VAR_index, VAR_this, VAR_top, exports, _ref, _ref1,
    __hasProp = {}.hasOwnProperty;

  _ref = require('../Core/Constants').Constants, GLOB_default = _ref.GLOB_default, VAR_context = _ref.VAR_context, VAR_count = _ref.VAR_count, VAR_index = _ref.VAR_index, VAR_this = _ref.VAR_this, VAR_top = _ref.VAR_top, STRING_empty = _ref.STRING_empty;

  Expression = require('./Expression/Javascript').Javascript;

  exports = (_ref1 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref1 : this;

  exports.Context = Context = (function() {
    var _compile;

    Context.prototype._variables = {};

    Context.prototype._data = null;

    function Context(data, parent) {
      var name, value, variables;
      variables = parent != null ? parent._variables : Context._globals;
      for (name in variables) {
        if (!__hasProp.call(variables, name)) continue;
        value = variables[name];
        this._variables[name] = value;
      }
      this._variables[VAR_this] = data;
      this._variables[VAR_context] = this;
      this._data = data != null ? data : STRING_empty;
      if (parent == null) {
        this._variables[VAR_top] = this._data;
      }
    }

    Context.prototype.execute = function(fn, template) {
      var e;
      try {
        return fn.call(template, this._variables, this._data);
      } catch (_error) {
        e = _error;
        console.log("Error " + e + " while executing " + fn + " on " + template);
      }
      return Context._globals[GLOB_default];
    };

    Context.prototype.clone = function(data, index, count) {
      var ret;
      ret = Context.create(data, this);
      ret.set(VAR_index, index);
      ret.set(VAR_count, count);
      return ret;
    };

    Context.prototype.set = function(name, value) {
      this._variables[name] = value;
    };

    Context.prototype.get = function(name) {
      return this._variables[name];
    };

    Context.compile = _compile = Expression.get().evaluateToFunction;

    Context.prototype.evaluate = function(expression, template) {
      return this.execute(_compile(expression), template);
    };

    Context._globals = {};

    Context.setGlobal = function(name, value) {
      return Context._globals[name] = value;
    };

    Context.setGlobal(GLOB_default, null);

    Context._recycled = [];

    Context.create = function(data, parent) {
      var instance;
      if (Context._recycled.length === 0) {
        return new Context(data, parent);
      }
      instance = Context._recycle.pop();
      Context.call(instance, data, parent);
      return instance;
    };

    Context.recycle = function(instance) {
      var name, _ref2;
      _ref2 = instance._variables;
      for (name in _ref2) {
        if (!__hasProp.call(_ref2, name)) continue;
        delete instance._variables[name];
      }
      instance._data = null;
      Context._recycled.push(instance);
    };

    return Context;

  })();

}).call(this);

//# sourceMappingURL=Context.map
