// Generated by CoffeeScript 1.6.3
(function() {
  var Action, InnerAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Action = require('goatee/Core/Action');

  exports.InnerAction = InnerAction = (function(_super) {
    __extends(InnerAction, _super);

    function InnerAction() {
      _ref = InnerAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return InnerAction;

  })(Action);

}).call(this);
