// Generated by CoffeeScript 1.6.3
(function() {
  var Action, OuterAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Action = require('goatee/Core/Action');

  exports.OuterAction = OuterAction = (function(_super) {
    __extends(OuterAction, _super);

    function OuterAction() {
      _ref = OuterAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return OuterAction;

  })(Action);

}).call(this);
