// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Document, ElementTraversal, constants, node, root;

  constants = require('goatee/Core/Constants');

  node = require('goatee/Dom/Node');

  ElementTraversal = require('goatee/Dom/Traversal/ElementTraversal');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Document = Document = (function() {
    Document.prototype.document = typeof window !== "undefined" && window !== null ? window.document : void 0;

    function Document(doc) {
      if (doc != null) {
        this.document = doc;
      }
    }

    Document.prototype.getElementById = function(id, doc) {
      return (doc || this.document).getElementById(id);
    };

    Document.prototype.createElement = function(name, doc) {
      return (doc || this.document).createElement(name);
    };

    Document.prototype.traverseElements = function(node, callback) {
      var visitor;
      visitor = new ElementTraversal(callback);
      visitor.run(node);
    };

    Document.prototype.hasAttribute = function(node, name) {
      if (node.hasAttribute != null) {
        return node.hasAttribute(name);
      }
      return this.getAttribute(name) != null;
    };

    Document.prototype.getAttribute = function(node, name) {
      return node.getAttribute(name);
    };

    Document.prototype.setAttribute = function(node, name, value) {
      node.setAttribute(name, value);
    };

    Document.prototype.removeAttribute = function(node, name) {
      node.removeAttribute(name);
    };

    Document.prototype.hasData = function(node, name) {
      var _ref;
      return ((_ref = node.dataset) != null ? _ref[name] : void 0) != null;
    };

    Document.prototype.getData = function(node, name) {
      return node.dataset[name];
    };

    Document.prototype.setData = function(node, name, value) {
      node.dataset[name] = value;
    };

    Document.prototype.removeData = function(node, name) {
      delete node.dataset[name];
    };

    Document.prototype.cloneNode = function(node) {
      return node.cloneNode(true);
    };

    Document.prototype.cloneElement = function(element) {
      return this.cloneNode(element);
    };

    Document.prototype.ownerDocument = function(node, doc) {
      if (node == null) {
        return doc || this.document;
      }
      if (node.nodeType == node.DOCUMENT_NODE) {
        return node;
      }
      return node.ownerDocument || doc || this.document;
    };

    Document.prototype.createTextNode = function(text, doc) {
      return (doc || this.document).createTextNode(text);
    };

    Document.prototype.appendChild = function(node, child) {
      return node.appendChild(child);
    };

    Document.prototype.displayDefault = function(node) {
      node.style[constants.CSS_display] = '';
    };

    Document.prototype.displayNone = function(node) {
      node.style[constants.CSS_display] = 'none';
    };

    Document.prototype.positionAbsolute = function(node) {
      node.style[constants.CSS_position] = 'absolute';
    };

    Document.prototype.insertBefore = function(newChild, oldChild) {
      return oldChild.parentNode.insertBefore(newChild, oldChild);
    };

    Document.prototype.replaceChild = function(newChild, oldChild) {
      return oldChild.parentNode.replaceChild(newChild, oldChild);
    };

    Document.prototype.removeNode = function(node) {
      return this.removeChild(node.parentNode, node);
    };

    Document.prototype.removeChild = function(node, child) {
      return node.removeChild(child);
    };

    return Document;

  })();

}).call(this);
