// Generated by CoffeeScript 1.7.1

/*
© Copyright 2013-2014 Stephan Jorek <stephan.jorek@gmail.com>  
© Copyright 2006 Google Inc. <http://www.google.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
 */

(function() {
  var CSS_display, CSS_position, DOCUMENT_NODE, Document, camelize, createTraversal, dashify, exports, _dataSetAvailable, _ref, _ref1, _ref2;

  _ref = require('../Core/Constants').Constants, CSS_display = _ref.CSS_display, CSS_position = _ref.CSS_position;

  DOCUMENT_NODE = require('./Node').Node.DOCUMENT_NODE;

  _ref1 = require('../Core/Utility').Utility, camelize = _ref1.camelize, dashify = _ref1.dashify;

  createTraversal = require('./Traversal/Level1NodeTypeMatcher').Level1NodeTypeMatcher.create;

  exports = (_ref2 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref2 : this;

  exports.Document = Document = {
    document: (typeof window !== "undefined" && window !== null ? window.document : void 0) || null,
    getElementById: function(id, doc) {
      return (doc || Document.document).getElementById(id);
    },
    createElement: function(name, doc) {
      return (doc || Document.document).createElement(name);
    },
    createTextNode: function(text, doc) {
      return (doc || Document.document).createTextNode(text);
    },
    traverseElements: function(node, callback) {
      return createTraversal(callback).run(node);
    },
    hasAttribute: (typeof HTMLElement !== "undefined" && HTMLElement !== null ? HTMLElement.prototype.hasAttribute : void 0) != null ? function(node, name) {
      return node.hasAttribute(name);
    } : function(node, name) {
      return Document.getAttribute(node, name) != null;
    },
    getAttribute: function(node, name) {
      return node.getAttribute(name);
    },
    setAttribute: function(node, name, value) {
      node.setAttribute(name, value);
    },
    removeAttribute: function(node, name) {
      node.removeAttribute(name);
    },
    hasData: (_dataSetAvailable = ((typeof HTMLElement !== "undefined" && HTMLElement !== null ? HTMLElement.prototype.dataset : void 0) != null) && (typeof DOMStringMap !== "undefined" && DOMStringMap !== null)) ? function(node, name) {
      var _ref3;
      return ((_ref3 = node.dataset) != null ? _ref3[camelize(name)] : void 0) != null;
    } : function(node, name) {
      return Document.hasAttribute(node, "data-" + (dashify(name)));
    },
    getData: _dataSetAvailable ? function(node, name) {
      if (node.dataset != null) {
        return node.dataset[camelize(name)];
      } else {
        return null;
      }
    } : function(node, name) {
      return Document.getAttribute(node, "data-" + (dashify(name)));
    },
    setData: _dataSetAvailable ? function(node, name, value) {
      node.dataset[camelize(name)] = value;
    } : function(node, name, value) {
      Document.setAttribute(node, "data-" + (dashify(name)), value);
    },
    removeData: _dataSetAvailable ? function(node, name) {
      delete node.dataset[camelize(name)];
    } : function(node, name) {
      Document.removeAttribute(node, "data-" + (dashify(name)));
    },
    cloneNode: function(node) {
      return node.cloneNode(true);
    },
    cloneElement: function(element) {
      return this.cloneNode(element);
    },
    ownerDocument: function(node, doc) {
      if (node == null) {
        return doc || Document.document;
      }
      if (node.nodeType == DOCUMENT_NODE) {
        return node;
      }
      return node.ownerDocument || doc || Document.document;
    },
    appendChild: function(node, child) {
      return node.appendChild(child);
    },
    displayDefault: function(node) {
      node.style[CSS_display] = '';
    },
    displayNone: function(node) {
      node.style[CSS_display] = 'none';
    },
    positionDefault: function(node) {
      node.style[CSS_position] = '';
    },
    positionAbsolute: function(node) {
      node.style[CSS_position] = 'absolute';
    },
    insertBefore: function(newChild, oldChild) {
      return oldChild.parentNode.insertBefore(newChild, oldChild);
    },
    replaceChild: function(newChild, oldChild) {
      return oldChild.parentNode.replaceChild(newChild, oldChild);
    },
    removeNode: function(node) {
      return Document.removeChild(node.parentNode, node);
    },
    removeChild: function(node, child) {
      return node.removeChild(child);
    }
  };

}).call(this);

//# sourceMappingURL=Document.map
