// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var NativeBrowserApi, Traversal, constants, node, root;

  constants = require('goatee/Core/Constants');

  node = typeof Node !== "undefined" && Node !== null ? Node : require('goatee/Dom/Node');

  Traversal = require('goatee/Dom/Traversal');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.NativeBrowserApi = NativeBrowserApi = {
    document: typeof window !== "undefined" && window !== null ? window.document : void 0,
    getElementById: function(id, doc) {
      return (doc || NativeBrowserApi.document).getElementById(id);
    },
    createElement: function(name, doc) {
      return (doc || NativeBrowserApi.document).createElement(name);
    },
    traverseElements: function(node, callback) {
      var visitor;
      visitor = new Traversal(callback);
      visitor.run(node);
    },
    getAttribute: function(node, name) {
      return node.getAttribute(name);
    },
    setAttribute: function(node, name, value) {
      node.setAttribute(name, value);
    },
    removeAttribute: function(node, name) {
      node.removeAttribute(name);
    },
    cloneNode: function(node) {
      return node.cloneNode(true);
    },
    cloneElement: function(element) {
      return NativeBrowserApi.cloneNode(element);
    },
    ownerDocument: function(node, doc) {
      if (node == null) {
        return doc || NativeBrowserApi.document;
      }
      if (node.nodeType == node.DOCUMENT_NODE) {
        return node;
      }
      return node.ownerDocument || doc || NativeBrowserApi.document;
    },
    createTextNode: function(text, doc) {
      return (doc || NativeBrowserApi.document).createTextNode(text);
    },
    appendChild: function(node, child) {
      return node.appendChild(child);
    },
    displayDefault: function(node) {
      node.style[constants.CSS_display] = '';
    },
    displayNone: function(node) {
      node.style[constants.CSS_display] = 'none';
    },
    positionAbsolute: function(node) {
      node.style[constants.CSS_position] = 'absolute';
    },
    insertBefore: function(newChild, oldChild) {
      return oldChild.parentNode.insertBefore(newChild, oldChild);
    },
    replaceChild: function(newChild, oldChild) {
      return oldChild.parentNode.replaceChild(newChild, oldChild);
    },
    removeNode: function(node) {
      return NativeBrowserApi.removeChild(node.parentNode, node);
    },
    removeChild: function(node, child) {
      return node.removeChild(child);
    }
  };

}).call(this);
