// Generated by CoffeeScript 1.6.3
(function() {
  var Node, Traversal;

  Node = Node || require('goatee/Dom/Node');

  exports.Traversal = Traversal = (function() {
    function Traversal(visitor) {
      this.visitor = visitor;
    }

    Traversal.prototype.run = function(root) {
      var _results;
      this.queue = [root];
      _results = [];
      while (this.queue.length > 0) {
        _results.push(this.process(this.queue.shift()));
      }
      return _results;
    };

    Traversal.prototype.process = function(node) {
      var child, _results;
      this.visitor.process(node);
      child = node.firstChild;
      _results = [];
      while (child) {
        if (child.nodeType === Node.ELEMENT_NODE) {
          this.queue.push(child);
        }
        _results.push(child = child.nextSibling);
      }
      return _results;
    };

    return Traversal;

  })();

}).call(this);
