// Generated by CoffeeScript 1.6.3
(function() {
  var Visitor;

  exports.Visitor = Visitor = (function() {
    function Visitor(manager) {
      this.manager = manager;
    }

    Visitor.prototype.process = function(node) {};

    return Visitor;

  })();

}).call(this);
