// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Coffee, Coffeescript, Constants, Javascript, Utility, root, _instance, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Coffee = require('coffee-script');

  Constants = require('goatee/Core/Constants').Constants;

  Utility = require('goatee/Core/Utility').Utility;

  Javascript = require('goatee/Action/Compiler/Javascript').Javascript;

  root = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  /*
  Coffeescript
  
  @class
  @namespace goatee.Action.Compiler
  */


  root.Coffeescript = Coffeescript = (function(_super) {
    var _expressionCache;

    __extends(Coffeescript, _super);

    function Coffeescript(options) {
      this.options = options != null ? options : {
        bare: true,
        inline: true,
        sourceMap: false,
        shiftLine: false
      };
    }

    _expressionCache = {};

    Coffeescript.prototype.evaluateExpression = function(expression) {
      var js;
      ((js = _expressionCache[expression]) != null) || (js = _expressionCache[expression] = Coffee.compile(expression, this.options));
      return Coffeescript.__super__.evaluateExpression.call(this, js);
    };

    return Coffeescript;

  })(Javascript);

  _instance = Coffeescript.instance = null;

  Coffeescript.get = function() {
    return _instance != null ? _instance : (_instance = new Coffeescript);
  };

}).call(this);

/*
//@ sourceMappingURL=Coffeescript.map
*/
