// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Composite, InMemory, constant, doc, root;

  constant = require('goatee/Core/Constants');

  doc = require('goatee/Dom/Document');

  InMemory = require('goatee/Core/InstructionCache/InMemory');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Composite = Composite = (function() {
    function Composite(caches) {
      this.caches = caches;
      this.caches = caches != null ? caches : [new ObjectPropertyCache, new InMemoryCache, new DomDataAttributeCache, new DomElementAttributeCache];
    }

    Composite.prototype.has = function(node, id) {
      var cache, _i, _len, _ref;
      _ref = this.caches;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cache = _ref[_i];
        if (cache.has(node, id)) {
          return true;
        }
      }
      return false;
    };

    Composite.prototype.get = function(node, id) {
      var cache, data, _i, _len, _ref;
      _ref = this.caches;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cache = _ref[_i];
        data = cache.get(node, id);
        if (data != null) {
          return data;
        }
      }
      return null;
    };

    Composite.prototype.set = function(node, id, value) {
      var cache, _i, _len, _ref;
      _ref = this.caches;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cache = _ref[_i];
        cache.set(node, id, value);
      }
    };

    return Composite;

  })();

}).call(this);
