// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var DomElementAttribute, InMemory, constant, doc, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  constant = require('goatee/Core/Constants');

  doc = require('goatee/Dom/Document');

  InMemory = require('goatee/Core/InstructionCache/InMemory');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.DomElementAttribute = DomElementAttribute = (function(_super) {
    __extends(DomElementAttribute, _super);

    function DomElementAttribute() {
      _ref = DomElementAttribute.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    DomElementAttribute.prototype.add = function(node, id, value) {
      dom.setAttribute(node, constant.ATT_jstcache, id);
      DomElementAttribute.__super__.add.call(this, id, value);
    };

    DomElementAttribute.prototype.has = function(node) {
      return dom.hasAttribute(node, constant.ATT_jstcache);
    };

    DomElementAttribute.prototype.get = function(node) {
      var id;
      id = dom.getAttribute(node, constant.ATT_jstcache);
      return DomElementAttribute.__super__.get.call(this, id);
    };

    DomElementAttribute.prototype.set = function(node, value) {
      var id;
      id = dom.getAttribute(node, constant.ATT_jstcache);
      DomElementAttribute.__super__.set.call(this, id, value);
    };

    return DomElementAttribute;

  })(InMemory);

}).call(this);
