// Generated by CoffeeScript 1.6.3
(function() {
  var PseudoStrictWithStatementFunction, WithStatementFunction, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WithStatementFunction = require('./WithStatementFunction').WithStatementFunction;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.PseudoStrictWithStatementFunction = PseudoStrictWithStatementFunction = (function(_super) {
    __extends(PseudoStrictWithStatementFunction, _super);

    function PseudoStrictWithStatementFunction() {
      _ref = PseudoStrictWithStatementFunction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PseudoStrictWithStatementFunction.prototype.build = function(expression, scope) {
      return PseudoStrictWithStatementFunction.__super__.build.call(this, "(function(){\"use strict\"; return " + expression + "}).call(this)");
    };

    return PseudoStrictWithStatementFunction;

  })(WithStatementFunction);

}).call(this);
