// Generated by CoffeeScript 1.6.3
(function() {
  var CHAR_comma, WithStatementFunction, WithStatementFunctionFromFunction, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CHAR_comma = require('../../Core/Constants').Constants.CHAR_comma;

  WithStatementFunction = require('./WithStatementFunction').WithStatementFunction;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WithStatementFunctionFromFunction = WithStatementFunctionFromFunction = (function(_super) {
    __extends(WithStatementFunctionFromFunction, _super);

    function WithStatementFunctionFromFunction() {
      _ref = WithStatementFunctionFromFunction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    WithStatementFunctionFromFunction.prototype.compile = function(args, code) {
      return Function("return function(" + (args.implode(CHAR_comma)) + ") { " + code + " }")();
    };

    return WithStatementFunctionFromFunction;

  })(WithStatementFunction);

}).call(this);
