// Generated by CoffeeScript 1.6.3
(function() {
  var CHAR_comma, WithStatementFunction, WithStatementFunctionFromEvaluation, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CHAR_comma = require('../../Core/Constants').Constants.CHAR_comma;

  WithStatementFunction = require('./WithStatementFunction').WithStatementFunction;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WithStatementFunctionFromEvaluation = WithStatementFunctionFromEvaluation = (function(_super) {
    __extends(WithStatementFunctionFromEvaluation, _super);

    function WithStatementFunctionFromEvaluation() {
      _ref = WithStatementFunctionFromEvaluation.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    WithStatementFunctionFromEvaluation.prototype.compile = function(args, code) {
      return eval("code = function(" + (args.implode(CHAR_comma)) + ") { " + code + " }");
    };

    return WithStatementFunctionFromEvaluation;

  })(WithStatementFunction);

}).call(this);
