// Generated by CoffeeScript 1.6.3
(function() {
  var WithStatementFunction, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WithStatementFunction = WithStatementFunction = (function() {
    function WithStatementFunction() {}

    WithStatementFunction.prototype._cache = {};

    WithStatementFunction.prototype.build = function(code) {
      var args;
      if (this._cache[code] != null) {
        return this._cache[code];
      }
      code = "return " + code;
      args = scope.map(function(object) {
        var name;
        name = "__" + object.name + "__";
        code = "with(" + name + ") { " + code + " }";
        return name;
      });
      args.push(code);
      return Function.apply(null, args);
    };

    return WithStatementFunction;

  })();

}).call(this);
