// Generated by CoffeeScript 1.6.3
(function() {
  var WithStatementFunction, root,
    __slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WithStatementFunction = WithStatementFunction = (function() {
    function WithStatementFunction() {}

    WithStatementFunction.prototype._cache = {};

    WithStatementFunction.prototype.bind = function() {
      var expression, scope;
      expression = arguments[0], scope = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this._cache[expression] || (this._cache[expression] = this.build(code, scope));
    };

    WithStatementFunction.prototype.build = function(expression, scope) {
      var args, code, index, name, object;
      code = "return " + expression;
      args = (function() {
        var _i, _len, _results;
        _results = [];
        for (object = _i = 0, _len = scope.length; _i < _len; object = ++_i) {
          index = scope[object];
          name = "__scope" + index + "__";
          code = "with(" + name + ") { " + code + " }";
          _results.push(name);
        }
        return _results;
      })();
      return this.compile(args, code);
    };

    WithStatementFunction.prototype.compile = function(args, code) {
      args.push(code);
      return Function.apply(null, args);
    };

    return WithStatementFunction;

  })();

}).call(this);
