// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var CHAR_comma, PropertyReferenceArgument, root,
    __slice = [].slice;

  CHAR_comma = require('../../Core/Constants').Constants.CHAR_comma;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.PropertyReferenceArgument = PropertyReferenceArgument = (function() {
    var _cache;

    function PropertyReferenceArgument() {}

    _cache = {};

    PropertyReferenceArgument.prototype.bind = function() {
      var code, scope;
      code = arguments[0], scope = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.build(code).apply(scope[0], scope);
    };

    PropertyReferenceArgument.prototype.build = function(code) {
      var self;
      self = this;
      return function() {
        var args, key, map, object, scope, vals, _i, _len;
        scope = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        map = {};
        args = [];
        vals = [];
        for (_i = 0, _len = scope.length; _i < _len; _i++) {
          object = scope[_i];
          for (key in object) {
            if (map[key] != null) {
              continue;
            }
            map[key] = args.length;
            args.push(key);
            vals.push(object[key]);
          }
        }
        return self.compile(args, code).apply(this, vals);
      };
    };

    PropertyReferenceArgument.prototype.compile = function(args, code) {
      var fn, id;
      id = "(" + (args.join(',')) + ") -> " + code;
      if ((fn = _cache[id]) != null) {
        return fn;
      }
      args.push("return " + code);
      return _cache[id] = Function.apply(null, args);
    };

    return PropertyReferenceArgument;

  })();

}).call(this);
