// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var CHAR_comma, PropertyReferenceArgument, PropertyReferenceArgumentRecycle, arrayClear, exports, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  CHAR_comma = require('../../Core/Constants').Constants.CHAR_comma;

  PropertyReferenceArgument = require('./PropertyReferenceArgument').PropertyReferenceArgument;

  arrayClear = require('../../Core/Constants').Utility.arrayClear;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.PropertyReferenceArgumentRecycle = PropertyReferenceArgumentRecycle = (function(_super) {
    var _args, _clearMap, _collectProperties, _map, _vals;

    __extends(PropertyReferenceArgumentRecycle, _super);

    function PropertyReferenceArgumentRecycle() {
      _ref1 = PropertyReferenceArgumentRecycle.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    _map = {};

    _args = [];

    _vals = [];

    _clearMap = function(key) {
      delete _map[key];
    };

    _collectProperties = function(object) {
      var key;
      for (key in object) {
        if (_map[key] != null) {
          continue;
        }
        _map[key] = _args.length;
        _args.push(key);
        _vals.push(object[key]);
      }
    };

    PropertyReferenceArgumentRecycle.prototype.build = function(code) {
      var self;
      self = this;
      return function() {
        var scope;
        scope = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        arrayClear(_args);
        arrayClear(_vals);
        scope.map(_collectProperties);
        _args.map(_clearMap);
        return self.compile(_args, code).apply(this, _vals);
      };
    };

    return PropertyReferenceArgumentRecycle;

  })(PropertyReferenceArgument);

}).call(this);

/*
//@ sourceMappingURL=PropertyReferenceArgumentRecycle.map
*/
