// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var WithStatement, root,
    __slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WithStatement = WithStatement = (function() {
    function WithStatement() {}

    WithStatement.prototype._cache = {};

    WithStatement.prototype.bind = function() {
      var code, scope;
      code = arguments[0], scope = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.buildMany(code).apply(scope[0], scope);
    };

    WithStatement.prototype.build = function(code) {
      var self;
      self = this;
      return function() {
        var args, id, index, name, object, scope;
        scope = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        code = "return " + code;
        args = (function() {
          var _i, _len, _results;
          _results = [];
          for (object = _i = 0, _len = scope.length; _i < _len; object = ++_i) {
            index = scope[object];
            name = "__scope" + index + "__";
            code = "with(" + name + ") " + code;
            _results.push(name);
          }
          return _results;
        })();
        id = self.identify(args, code);
        return _cache[id] || (_cache[id] = self.compile(args, code));
      };
    };

    WithStatement.prototype.identify = function(args, code) {
      return "(" + (args.join(',')) + ") -> (" + code + ")";
    };

    WithStatement.prototype.compile = function(id, args, code) {
      args.push(code);
      return Function.apply(null, args);
    };

    return WithStatement;

  })();

}).call(this);
