// Generated by CoffeeScript 1.6.3
(function() {
  var Action;

  exports.Action = Action = (function() {
    function Action() {}

    Action.prototype.process = function(processor, context, template, attribute) {
      throw new Exception('Missing “process”-method implementation');
      return false;
    };

    return Action;

  })();

}).call(this);
