// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var AttributeMap, RuleMap, dashify, root, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RuleMap = require('./RuleMap').RuleMap;

  dashify = require('./Utility').Utility.dashify;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.AttributeMap = AttributeMap = (function(_super) {
    __extends(AttributeMap, _super);

    function AttributeMap() {
      _ref = AttributeMap.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AttributeMap.prototype.normalizeKey = function(string) {
      return dashify(AttributeMap.__super__.normalizeKey.call(this, string));
    };

    return AttributeMap;

  })(RuleMap);

  AttributeMap.parse = function(text, _map) {
    return RuleMap.parse(text, _map != null ? _map : new AttributeMap);
  };

}).call(this);
