// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var RuleMap, Utility, root;

  Utility = require('./Utility').Utility;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.RuleMap = RuleMap = (function() {
    function RuleMap(rules, priorize) {
      this.rules = rules;
      this.priorize = priorize;
      if (this.rules == null) {
        this.rules = {};
      }
      if (this.priorize == null) {
        this.priorize = {};
      }
    }

    return RuleMap;

  })();

  RuleMap.parse = function(text) {
    var add, buffer, char, error, i, important, index, j, name, priorize, rules, state;
    i = 0;
    j = i;
    state = "name";
    buffer = "";
    char = "";
    rules = {};
    priorize = {};
    important = false;
    add = function(name) {
      if (!(name in rules) || important || !(name in priorize)) {
        rules[name] = Utility.trim(buffer);
        if (important) {
          return priorize[name] = true;
        }
      }
    };
    error = function() {
      return "“" + text.slice(0, i) + '»»»' + text.charAt(i) + '«««' + text.slice(i + 1) + ("” (state: " + state + ", position: " + i + ", character: “" + char + "”)");
    };
    for (char = text.charAt(i); (char = text.charAt(i)) !== ""; i++) {;
    switch (char) {
      case " ":
      case "\t":
      case "\r":
      case "\n":
      case "\f":
        if (state === "value" && !important) {
          buffer += char;
        }
        continue;
        break;
      case "'":
      case '"':
        if (important) {
          throw "unexpected content after important declaration: " + (error());
        } else if (state === "value") {
          j = i + 1;
          while (index = text.indexOf(char, j) + 1) {
            console.log(1, index, 2, j, 3, text.charAt(index - 2), 4, text.slice(i, index - 1));
            if (text.charAt(index - 2) !== "\\" || /[^\\](\\\\)*$/.test(text.slice(i, index - 1))) {
              break;
            }
            j = index;
          }
          if (index === 0) {
            throw "Missing closing string: " + (error());
          }
          buffer += text.slice(i, index);
          i = index - 1;
          continue;
        } else {
          throw "unexpected string: " + (error());
        }
        break;
      case "/":
        if (text.charAt(i + 1) === "*") {
          i += 2;
          index = text.indexOf("*/", i);
          if (index === -1) {
            throw "Missing closing comment: " + (error());
          }
          i = index + 1;
          continue;
        } else if (important) {
          throw "unexpected content after important declaration: " + (error());
        } else {
          buffer += char;
          continue;
        }
        break;
      case ":":
        if (state === "name") {
          name = Utility.trim(buffer);
          if (name === "") {
            throw "missing identifer: " + (error());
          }
          buffer = "";
          state = "value";
          continue;
        } else if (important) {
          throw "unexpected content after important declaration: " + (error());
        } else {
          buffer += char;
          continue;
        }
        break;
      case "!":
        if (state === "value" && text.indexOf("!important", i) === i) {
          if (important) {
            throw "unexpected important after another important declaration: " + (error());
          }
          important = true;
          i += 9;
          continue;
        } else if (important) {
          throw "unexpected content after important declaration: " + (error());
        } else {
          buffer += char;
          continue;
        }
        break;
      case ";":
        if (state === "name") {
          continue;
        }
        if (state === "value") {
          add(name);
          important = false;
          buffer = "";
          state = "name";
          continue;
        } else if (important) {
          throw "unexpected content after important declaration: " + (error());
        } else {
          buffer += char;
          continue;
        }
        break;
      default:
        if (important) {
          throw "unexpected content after important declaration: " + (error());
        }
        buffer += char;
        continue;
        break;
    }
    };
    if (state === "value") {
      add(name);
    }
    return new RuleMap(rules, priorize);
  };

}).call(this);
