// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var RuleMap, Utility, root;

  Utility = require('goatee/Core/Utility').Utility;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.RuleMap = RuleMap = (function() {
    function RuleMap(rules, priorize) {
      this.rules = rules;
      this.priorize = priorize;
      if (this.rules == null) {
        this.rules = {};
      }
      if (this.priorize == null) {
        this.priorize = {};
      }
    }

    return RuleMap;

  })();

  RuleMap.parse = function(text) {
    var add, buffer, char, i, important, index, j, name, priorize, rules, state;
    i = 0;
    j = i;
    state = "name";
    buffer = "";
    char = "";
    rules = {};
    priorize = {};
    important = false;
    add = function(name) {
      if (!(name in rules) || important || !(name in priorize)) {
        rules[name] = Utility.trim(buffer);
        if (important) {
          return priorize[name] = true;
        }
      }
    };
    for (char = text.charAt(i); char !== ""; i++) {;
    switch (char) {
      case " ":
      case "\t":
      case "\r":
      case "\n":
      case "\f":
        if (state === "value" && !important) {
          buffer += char;
        }
        break;
      case "'":
      case '"':
        if (important) {
          throw new SyntaxError('unexpected content after important declaration');
        } else if (state === "value") {
          j = i + 1;
          while (index = text.indexOf(char, j) + 1) {
            if (text.charAt(index - 1) !== '\\' || text.slice(i, index - 1).test(/[^\\](\\\\)*$/)) {
              break;
            }
            j = index;
          }
          if (index === 0) {
            throw new SyntaxError(char + ' is missing');
          }
          buffer += text.slice(i, index);
          i = index - 1;
        } else {
          throw new SyntaxError('unexpected string');
        }
        break;
      case "/":
        if (text.charAt(i + 1) === "*") {
          i += 2;
          index = text.indexOf("*/", i);
          if (index === -1) {
            throw new SyntaxError("Missing */");
          } else {
            i = index + 1;
          }
        } else if (important) {
          throw new SyntaxError('unexpected content after important declaration');
        } else {
          buffer += char;
        }
        break;
      case ":":
        if (state === "name") {
          name = Utility.trim(buffer);
          buffer = "";
          state = "value";
        } else if (important) {
          throw new SyntaxError('unexpected content after important declaration');
        } else {
          buffer += char;
        }
        break;
      case "!":
        if (state === "value" && ruleText.indexOf("!important", i) === i) {
          if (important) {
            throw new SyntaxError("unexpected important after another important declaration");
          }
          important = true;
          i += 9;
        } else if (important) {
          throw new SyntaxError('unexpected content after important declaration');
        } else {
          buffer += char;
        }
        break;
      case ";":
        if (state === "value") {
          add(name);
          important = false;
          buffer = "";
          state = "name";
        } else if (important) {
          throw new SyntaxError('unexpected content after important declaration');
        } else {
          buffer += char;
        }
        break;
      default:
        if (important) {
          throw new SyntaxError('unexpected content after important declaration');
          break;
        }
        buffer += char;
        break;
    }
    };
    if (state === "value") {
      add(name);
    }
    return new RuleMap(rules, priorize);
  };

}).call(this);
