// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>  
© Copyright 2006 Google Inc. <http://www.google.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var CHAR_dash, REGEXP_camelize, REGEXP_dashify, REGEXP_trim, REGEXP_trimLeft, REGEXP_trimRight, TYPE_number, Utility, exports, _ref, _ref1,
    __slice = [].slice;

  _ref = require('./Constants').Constants, CHAR_dash = _ref.CHAR_dash, TYPE_number = _ref.TYPE_number, REGEXP_trim = _ref.REGEXP_trim, REGEXP_trimLeft = _ref.REGEXP_trimLeft, REGEXP_trimRight = _ref.REGEXP_trimRight, REGEXP_camelize = _ref.REGEXP_camelize, REGEXP_dashify = _ref.REGEXP_dashify;

  exports = (_ref1 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref1 : this;

  exports.Utility = Utility = {
    isArray: function(value) {
      return (value.length != null) && typeof value.length === TYPE_number;
    },
    arraySlice: function(array, start, end) {
      return Function.prototype.call.apply(Array.prototype.slice, arguments);
    },
    arrayClear: function(array) {
      array.length = 0;
    },
    parseInt10: function(string) {
      return parseInt(string, 10);
    },
    bind: function() {
      var args, method, object;
      object = arguments[0], method = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      return function() {
        return method.apply(object, args);
      };
    },
    trim: String.prototype.trim != null ? function(string) {
      return string.trim();
    } : function(string) {
      return string.replace(REGEXP_trim, '');
    },
    trimLeft: String.prototype.trimLeft != null ? function(string) {
      return string.trimLeft();
    } : function(string) {
      return string.replace(REGEXP_trimLeft, '');
    },
    trimRight: String.prototype.trimRight != null ? function(string) {
      return string.trimRight();
    } : function(string) {
      return string.replace(REGEXP_trimRight, '');
    },
    camelize: (function() {
      var _camelize;
      _camelize = function(match, char, index, string) {
        return char.toUpperCase();
      };
      return function(string) {
        return string.replace(REGEXP_camelize, _camelize);
      };
    })(),
    dashify: (function() {
      var _dashify;
      _dashify = function(match, char, camel, index, string) {
        return char + CHAR_dash + camel.toLowerCase();
      };
      return function(string) {
        return string.replace(REGEXP_dashify, _dashify);
      };
    })()
  };

}).call(this);

/*
//@ sourceMappingURL=Utility.map
*/
