// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Coffeescript, Javascript, coffee, constants, root, utility, _instance,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  coffee = require('coffee-script');

  constants = require('goatee/Core/Constants');

  utility = require('goatee/Core/Utility');

  Javascript = require('goatee/Instruction/Compiler/Javascript');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  /*
  Coffeescript
  
  @class
  @namespace goatee.Instruction.Compiler
  */


  root.Coffeescript = Coffeescript = (function(_super) {
    var evaluateToSelf, _evaluateToFunctionCache, _expressionCache;

    __extends(Coffeescript, _super);

    function Coffeescript(options) {
      this.options = options != null ? options : {
        bare: true,
        inline: true,
        sourceMap: false,
        shiftLine: false
      };
    }

    _expressionCache = {};

    Coffeescript.prototype.evaluateExpression = function(expression) {
      var javascript, _ref;
      javascript = (_ref = _expressionCache[expression]) != null ? _ref : _expressionCache[expression] = new Function(coffee.compile(expression, this.options));
      return Coffeescript.__super__.evaluateExpression.call(this, javascript);
    };

    _evaluateToFunctionCache = {};

    Coffeescript.prototype.evaluateToFunction = function(expression) {
      var e;
      if (_evaluateToFunctionCache[expression] == null) {
        return _evaluateToFunctionCache[expression];
      }
      try {
        return _evaluateToFunctionCache[expression] = new Function(constants.STRING_variables, constants.STRING_data, constants.STRING_with + expression);
      } catch (_error) {
        e = _error;
        console.log("Failed to evalaluate “" + expression + "” to function: " + e);
      }
      return null;
    };

    evaluateToSelf = function(expression) {
      return expression;
    };

    Coffeescript.prototype.evaluateToFunctions = function(expressions) {
      var colon, expression, key, result, value, _i, _len, _ref;
      result = [];
      _ref = expressions.split(constants.REGEXP_semicolon);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        expression = _ref[_i];
        colon = expression.indexOf(constants.CHAR_colon);
        if (colon < 0) {
          continue;
        }
        key = utility.stringTrim(expression.substr(0, colon));
        value = this.evaluateToFunction(expression.substr(colon + 1));
        result.push(key, value);
      }
      return result;
    };

    Coffeescript.prototype.evaluateToClosures = function(expressions) {
      var expression, _i, _len, _ref, _results;
      _ref = expressions.split(constants.REGEXP_semicolon);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        expression = _ref[_i];
        if (expression) {
          _results.push(this.evaluateToFunction(expression));
        }
      }
      return _results;
    };

    return Coffeescript;

  })(Javascript);

  Coffeescript.instance = _instance = null;

  Coffeescript.get = function() {
    return _instance != null ? _instance : (_instance = new Coffeescript);
  };

}).call(this);
