// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2006 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Javascript, constants, instance, root, utility;

  constants = require('goatee/Core/Constants');

  utility = require('goatee/Core/Utility');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  /*
  Javascript
  
  @class
  @namespace goatee.Instruction.Compiler
  */


  root.Javascript = Javascript = (function() {
    var evaluateToSelf, _evaluateToFunctionCache;

    function Javascript() {}

    Javascript.prototype.evaluate = function(expression) {
      var e;
      try {
        this.evaluateExpression(expression);
      } catch (_error) {
        e = _error;
        console.log("Failed to evaluate “" + expression + "”: " + e);
      }
      return null;
    };

    Javascript.prototype.evaluateExpression = function(expression) {
      /*
      NOTE(mesch): An alternative idiom would be:
      
        eval('(' + expr + ')');
      
      Note that using the square brackets as below, "" evals to undefined.
      The alternative of using parentheses does not work when evaluating
      function literals in IE.
      e.g. eval("(function() {})") returns undefined, and not a function
      object, in IE.
      
      NOTE(sjorek): Due to the underlying coffescript-specific language
      agnostics we deliberatly fall back to vanilla javascript here.
      */

      return eval('[' + expression + '][0]');
    };

    _evaluateToFunctionCache = {};

    Javascript.prototype.evaluateToFunction = function(expression) {
      var e;
      if (_evaluateToFunctionCache[expression] == null) {
        return _evaluateToFunctionCache[expression];
      }
      try {
        return _evaluateToFunctionCache[expression] = Function(constants.STRING_variables, constants.STRING_data, constants.STRING_with + expression);
      } catch (_error) {
        e = _error;
        console.log("Failed to evalaluate “" + expression + "” to function: " + e);
      }
      return null;
    };

    evaluateToSelf = function(expression) {
      return expression;
    };

    Javascript.prototype.evaluateToFunctions = function(expressions) {
      var colon, expression, key, result, value, _i, _len, _ref;
      result = [];
      _ref = expressions.split(constants.REGEXP_semicolon);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        expression = _ref[_i];
        colon = expression.indexOf(constants.CHAR_colon);
        if (colon < 0) {
          continue;
        }
        key = utility.stringTrim(expression.substr(0, colon));
        value = this.evaluateToFunction(expression.substr(colon + 1));
        result.push(key, value);
      }
      return result;
    };

    Javascript.prototype.evaluateToClosures = function(expressions) {
      var expression, _i, _len, _ref, _results;
      _ref = expressions.split(constants.REGEXP_semicolon);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        expression = _ref[_i];
        if (expression) {
          _results.push(this.evaluateToFunction(expression));
        }
      }
      return _results;
    };

    return Javascript;

  })();

  Javascript.instance = instance = null;

  Javascript.get = function() {
    return instance != null ? instance : (instance = new Javascript);
  };

}).call(this);
