// Generated by CoffeeScript 1.6.3
(function() {
  var OuterAction, SelectAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OuterAction = require('goatee/Action/OuterAction');

  exports.SelectAction = SelectAction = (function(_super) {
    __extends(SelectAction, _super);

    function SelectAction() {
      _ref = SelectAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return SelectAction;

  })(OuterAction);

}).call(this);
