// Generated by CoffeeScript 1.6.3
(function() {
  var ContentAction, InnerAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InnerAction = require('goatee/Action/InnerAction');

  exports.ContentAction = ContentAction = (function(_super) {
    __extends(ContentAction, _super);

    function ContentAction() {
      _ref = ContentAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return ContentAction;

  })(InnerAction);

}).call(this);
