// Generated by CoffeeScript 1.6.3
(function() {
  var InnerAction, SetAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InnerAction = require('goatee/Action/InnerAction');

  exports.SetAction = SetAction = (function(_super) {
    __extends(SetAction, _super);

    function SetAction() {
      _ref = SetAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return SetAction;

  })(InnerAction);

}).call(this);
