// Generated by CoffeeScript 1.6.3
(function() {
  var InnerAction, ShowAction, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InnerAction = require('goatee/Action/InnerAction');

  exports.ShowAction = ShowAction = (function(_super) {
    __extends(ShowAction, _super);

    function ShowAction() {
      _ref = ShowAction.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return ShowAction;

  })(InnerAction);

}).call(this);
